-- Adicionar campos descritivos à tabela Character
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS sire TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS ambition TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS desire TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS "predatorType" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS "apparentAge" INTEGER;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS appearance TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS personality TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS history TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS goals TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS weakness TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS touchstones TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS convictions TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS "alliesContacts" TEXT;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS possessions TEXT;
